version: "3.8"
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5000:5000
      - 6001:6001
    volumes:
      - ./api:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: python ./server.py
    tty: true
    stdin_open: true
    environment:
      DOCKER_HOST_PATH: ${PWD}
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: "npm run start"
    stdin_open: true