version: "3.8"
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5000:5000
      - 6001:6001
    volumes:
      - ./api:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: python ./server.py
    tty: true
    stdin_open: true
    environment:
      DOCKER_HOST_PATH: ${PWD}
  # web:
  #   build: web
  #   restart: always
  #   ports:
  #     - 80:80